Vagrant.configure("2") do |config|

  # ==========================================
  # Machine 1: db01 (CentOS Stream 9)
  # ==========================================
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.network "private_network", ip: "192.168.45.15"
    db01.vm.network "public_network", dev: "enp39s0", mode: "bridge", type: "direct"
    
    db01.vm.provider "libvirt" do |libvirt|
      libvirt.memory = "1024"
      libvirt.cpus = 2
      libvirt.nic_adapter_count = 8
    end

    db01.vm.provision "shell", inline: <<-SHELL
      yum install httpd wget unzip zip vim -y
      systemctl start httpd
      systemctl enable httpd
    SHELL
  end

  # ==========================================
  # Machine 2: web01 (Ubuntu 20.04)
  # ==========================================
  config.vm.define "web01" do |web01|
    web01.vm.box = "generic/ubuntu2004"
    web01.vm.network "private_network", ip: "192.168.45.20"
    web01.vm.network "public_network", dev: "enp39s0", mode: "bridge", type: "direct"
    
    web01.vm.provider "libvirt" do |libvirt|
      libvirt.memory = "1600"
      libvirt.cpus = 2
      libvirt.nic_adapter_count = 8
    end
  end 

end 
